name: Generate contribution snake

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_dots=#f3f0ff,#ddd6fe,#c4b5fd,#a78bfa,#7c3aed
            dist/github-snake-dark.svg?color_dots=#16161d,#ddd6fe,#c4b5fd,#a78bfa,#7c3aed
            dist/ocean.gif?color_snake=orange&color_dots=#16161d,#ddd6fe,#c4b5fd,#a78bfa,#7c3aed

      - name: Publish generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
